import { CountDownTimeType } from "./Enum";

export class EventCountDown{
  // private id : string;
  // private targetYear : number;
  // private targetMonth : number;
  // private targetDay : number;
  // private targetHour : number;
  // private targetMinute : number;
  // private targetSecond : number;
  // private targetTimeMillis : number;
  // private eventName : string;
  // private eventDetail : string;
  // private image : Resource | null;
  // private creatAtMillis : number;
  // private countDownTimeType : CountDownTimeType;
  // private isImportant : boolean;

}