// export class FontSizeInAlmanacAllData{
//   static readonly yiAndJiFontSize = 18;
//   static readonly yiAndJiContentFontSize = 15;
// }
//
// export class containerSizeInAlmanacAllData{
//   static readonly yiAndJiContainerWidth = 30;
//   static readonly yiAndJiContainerHeight = 30;
//   static readonly yiAndJiTextWidth = 320;
//   static readonly auto = 'auto';
// }
//
// export class containerBorderInAlmanacAllData{
//   static readonly yiAndJiContainerBorderRadius = 10;
// }
//
// export class containerGapInAlmanacAllData{
//   static readonly yiAndJiRowGap = 20;
//   static readonly yiAndJiGapInRow = 10;
//   static readonly yiJiAndGanzhiDateGap = 15;
//   static readonly wholePagePadding = 10;
// }
//
// export class stringConstantsInAlmanacAllData{
//   static readonly Yi = '宜';
//   static readonly Ji = '忌';
// }