export class BasicConstant{
  static readonly FULL_WIDTH = '100%';
  static readonly FULL_HEIGHT = '100%';
  static readonly HALF_WIDTH = '50%';
  static readonly HALF_HEIGHT = '50%';
  static readonly ONE_QUARTER = '25%';
  static readonly ONE_EIGHTH = '12.5%';
  static readonly ANIMATION_DURATION_LONG = 500;
  static readonly ANIMATION_DURATION_MEDIUM = 400;
  static readonly ANIMATION_DURATION_SHORT = 300;
  static readonly ANIMATION_SPEED_FASTER = 3.0;
  static readonly THIRTY_PERCENT = '30%';
  static readonly NINETY_FIVE_PERCENT = '95%'
  static readonly MONTH_NUMBER_PER_YEAR = 12;
  static readonly MONTH_DATASOURCE_INITIAL_INDEX = 6000;
  static readonly EIGHTY_PERCENTAGE = '80%';
  static readonly SIXTY_PERCENTAGE = '60%'
  static readonly MAX_LENGTH_TIME = 2;
}